import { WorkflowEntrypoint, type WorkflowEvent, type WorkflowStep } from "cloudflare:workers";

// These files are generated before Wrangler bundles this custom entrypoint.
// @ts-expect-error -- OpenNext build output is generated by npm run cf:build.
import openNextWorker from "./.open-next/worker.js";
// @ts-expect-error -- OpenNext build output is generated by npm run cf:build.
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
// @ts-expect-error -- OpenNext build output is generated by npm run cf:build.
import { runWithCloudflareRequestContext } from "./.open-next/cloudflare/init.js";

import { KNOWLEDGE_INDEX_EXECUTION_CONFIG } from "./src/lib/knowledge/config";
import { processKnowledgeIndexJob } from "./src/lib/knowledge/index-service";

type KnowledgeIndexWorkflowPayload = {
  jobId: string;
};

type KnowledgeIndexWorkflowEnv = CloudflareEnv & {
  KNOWLEDGE_INDEX_WORKFLOW: Workflow<KnowledgeIndexWorkflowPayload>;
};

/** Durable parsing, embedding and Vectorize activation beyond waitUntil(). */
export class KnowledgeIndexWorkflow extends WorkflowEntrypoint<
  KnowledgeIndexWorkflowEnv,
  KnowledgeIndexWorkflowPayload
> {
  async run(
    event: Readonly<WorkflowEvent<KnowledgeIndexWorkflowPayload>>,
    step: WorkflowStep,
  ) {
    const jobId = event.payload.jobId;
    if (!jobId || typeof jobId !== "string") throw new Error("Knowledge index job id is required.");

    await step.do(
      "index and activate knowledge document",
      {
        retries: { limit: 3, delay: "30 seconds", backoff: "exponential" },
        timeout: "12 minutes",
      },
      async () => {
        const request = new Request("https://erp.e3energy.com.au/__knowledge-index-workflow");
        await runWithCloudflareRequestContext(request, this.env, this.ctx, async () => {
          await processKnowledgeIndexJob(jobId, {
            workerId: `knowledge-workflow:${event.instanceId}`,
            leaseSeconds: KNOWLEDGE_INDEX_EXECUTION_CONFIG.workflowLeaseSeconds,
            deadlineAt: Date.now() + KNOWLEDGE_INDEX_EXECUTION_CONFIG.workflowProviderTimeoutMs,
            providerTimeoutMs: KNOWLEDGE_INDEX_EXECUTION_CONFIG.workflowProviderTimeoutMs,
          });
        });
        return { jobId };
      },
    );
  }
}

export default openNextWorker;
